USE TPCDS_CS;
CREATE UNIQUE INDEX customer_address_ui ON customer_address (ca_address_sk);  
CREATE UNIQUE INDEX customer_demographics_ui ON customer_demographics (cd_demo_sk);  
CREATE UNIQUE INDEX date_dim_ui ON date_dim  (d_date_sk);  
CREATE UNIQUE INDEX warehouse_ui ON warehouse  (w_warehouse_sk);  
CREATE UNIQUE INDEX ship_mode_ui ON  ship_mode (sm_ship_mode_sk);  
CREATE UNIQUE INDEX time_dim_ui ON time_dim  (t_time_sk);  
CREATE UNIQUE INDEX reason_ui ON  reason (r_reason_sk);  
CREATE UNIQUE INDEX income_band_ui ON income_band  (ib_income_band_sk);  
CREATE UNIQUE INDEX item_ui ON  item (i_item_sk);  
CREATE UNIQUE INDEX store_ui ON  store (s_store_sk);  
CREATE UNIQUE INDEX call_center_ui ON  call_center (cc_call_center_sk);  
CREATE UNIQUE INDEX customer_ui ON  customer (c_customer_sk);  
CREATE UNIQUE INDEX web_site_ui ON  web_site (web_site_sk);  
CREATE UNIQUE INDEX store_returns_ui ON  store_returns (sr_item_sk, sr_ticket_number);  
CREATE UNIQUE INDEX household_demographics_ui ON  household_demographics (hd_demo_sk);  
CREATE UNIQUE INDEX web_page_ui ON web_page  (wp_web_page_sk);  
CREATE UNIQUE INDEX promotion_ui ON  promotion (p_promo_sk);  
CREATE UNIQUE INDEX web_sales_ui ON web_sales  (ws_item_sk, ws_order_number);  
CREATE UNIQUE INDEX catalog_sales_ui ON catalog_sales  (cs_item_sk, cs_order_number);  
CREATE UNIQUE INDEX store_sales_ui ON store_sales  (ss_item_sk, ss_ticket_number);  
CREATE UNIQUE INDEX web_returns_ui ON web_returns  (wr_item_sk, wr_order_number);  
CREATE UNIQUE INDEX catalog_returns_ui ON  catalog_returns (cr_item_sk, cr_order_number);  
CREATE UNIQUE INDEX inventory_ui ON  inventory (inv_date_sk, inv_item_sk, inv_warehouse_sk);  
CREATE UNIQUE INDEX catalog_page_ui ON  catalog_page (cp_catalog_page_sk);  